version: '3.7'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    volumes:
      - ./data/zoo:/var/lib/zookeeper/data
    ports:
      - 2181:2181
    networks:
      - kafka-test0001

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - kafka-test0001
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.1.15:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.15:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    volumes:
      - ./data/kafka:/kafka
      
  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   networks:
  #     - kafka-test0001
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #     KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
  #     KAFKA_CLUSTERS_0_JMXPORT: 9997

networks:
  kafka-test0001:
    name: kafka-test0001
    external: false

# docker run -d -p 9092:9092 \
# -e KAFKA_ZOOKEEPER_CONNECT=192.168.1.15:2181 \
# -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.15:9092 \
# -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
# confluentinc/cp-kafka
